### ISSUE TITLE
Support Ledger Hardaware

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubConnect-v2#12]
Support Ledger for Polkadot network on web3-onboard
- [x] Connect with Ledger
- [x] Sign transaction
- [x] Add ledger for more network
  - [x] Kusama
  - [x] Polkadot Asset Hub
  - [x] Kusama Asset Hub

**Comment by haiyenvu23** [comment]
Bug related to this feature in issue https://github.com/Koniverse/SubWallet-Extension/issues/2639
