### ISSUE TITLE
Implement Demo Page

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubConnect-v2#14]
- [x] Connect Wallet
- [x] Polkadot Demo
  - [x] Sign message
  - [x] Sign transactino
  - [x] Import Metadata
- [x] EVM Demo
  - [x] Info
  - [x] Sign message
  - [x] Sign transaction

**Comment by saltict** [comment]
- [x] Fix Header logo
![image](https://github.com/Koniverse/web3-onboard/assets/11567273/acbf168d-ff8f-4059-8442-acd8f622faf5)

**Comment by saltict** [comment]
- [x] Lack of header and footer space
![image](https://github.com/Koniverse/web3-onboard/assets/11567273/e9c3fd50-cbc6-4633-ad53-8fa7ddbbc585)

**Comment by saltict** [comment]
- [x] Set max with for main container like design
![image](https://github.com/Koniverse/web3-onboard/assets/11567273/563d1905-3c99-43ea-a67e-d0a72775dbad)

**Comment by saltict** [comment]
- [x] Wrong notification position
![image](https://github.com/Koniverse/web3-onboard/assets/11567273/7436fafc-4535-4354-aa39-a6a38cec6e66)

**Comment by saltict** [comment]
- [x] Bug sign transaction without notification (just validate - don't send it to block chain)

**Comment by saltict** [comment]
- [x] Polkadot Asset Hub
- [x] Kussaa Asset Hub
- [x] Add Kusama
- [x] Remove HydraDX
- [x] Remove Astar
![image](https://github.com/Koniverse/web3-onboard/assets/11567273/2a7e0db8-134e-4528-a20c-9a217b6622af)

**Comment by saltict** [comment]
- [x] Sign transaction error (Substrate)
- [x] Sign transaction error (EVM)

**Comment by saltict** [comment]
- [x] Unknow when switch network

**Comment by haiyenvu23** [comment]
Bug related to this feature in issue https://github.com/Koniverse/SubWallet-Extension/issues/2639
