### ISSUE TITLE
Listing Screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubConnect-v2#5]
@Thiendekaco please list all screen with screen to this issue for UI re-design purponse

**Comment by Thiendekaco** [comment]
List all scree : 

**Connect screen** 

1. When generate qrCode : 

![Screenshot (514)](https://github.com/Koniverse/web3-onboard/assets/139972251/bd3a0c93-031f-484b-94dc-7e65f9ba35d6)

3. When not generate qrCode:


![Screenshot (527)](https://github.com/Koniverse/web3-onboard/assets/139972251/c25c778c-0e0b-467e-a5e9-dc6880190082)



5. When connecting the device is phone or short width:

![Screenshot (526)](https://github.com/Koniverse/web3-onboard/assets/139972251/aabb2e2b-5f0f-4a72-be92-40d1b432d5db)


![Screenshot (522)](https://github.com/Koniverse/web3-onboard/assets/139972251/138e07ee-6101-4d4f-8ebc-fe5507f2e7b8)

6. Connecting screen:


![Screenshot (529)](https://github.com/Koniverse/web3-onboard/assets/139972251/5ee6d48d-5a41-4600-a648-a4192a236008)

8. Reject connect screen:

![Screenshot (528)](https://github.com/Koniverse/web3-onboard/assets/139972251/32f75db8-62d1-4807-a286-03903db933a5)




10. Connected screen:

![Screenshot (516)](https://github.com/Koniverse/web3-onboard/assets/139972251/de728515-033a-49ad-9894-26c21de60727)





**Account center**

1.  When multiple accounts

![Screenshot (519)](https://github.com/Koniverse/web3-onboard/assets/139972251/088232c0-b9bc-47ca-86ee-48d5958b6442)


3. When open option

![Screenshot (525)](https://github.com/Koniverse/web3-onboard/assets/139972251/e06fd7dc-e6ef-474a-9dd8-44e1c93143af)

4.Notifications appear when performing tasks such as sign message, switch chain


![Screenshot (518)](https://github.com/Koniverse/web3-onboard/assets/139972251/ae2eeca2-2fe9-4620-a9d2-e72b4726e139)

![Screenshot (517)](https://github.com/Koniverse/web3-onboard/assets/139972251/e0ddc64b-99a0-4efb-b608-95ed7add611a)

![Screenshot (524)](https://github.com/Koniverse/web3-onboard/assets/139972251/f066ac2f-c56c-4ccf-ad1a-9d50f3bc36b0)



**Notification**

![notify-custom-example c6c907d1](https://github.com/Koniverse/web3-onboard/assets/139972251/1a129492-785e-4021-97e1-1e61d0c98925)
