### ISSUE TITLE
[UI] Implement new UI appereance

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubConnect-v2#9]
Update Connect Demo and web3-onboard with new design

**Comment by saltict** [comment]
@Thiendekaco please listing screens in this issue

**Comment by Thiendekaco** [comment]
- [x] Account center

![image](https://github.com/Koniverse/web3-onboard/assets/139972251/0801424c-cdcc-49c6-92a5-a86f9c5eedc8)

- [ ] Notification box

![image](https://github.com/Koniverse/web3-onboard/assets/139972251/67e640e0-a323-4275-b95a-a7e41f94d342)

- [ ] Scan account for hardware wallet

![Screenshot (605)](https://github.com/Koniverse/web3-onboard/assets/139972251/7458beb6-257c-4abd-ab5a-485b0c235722)

**Comment by saltict** [comment]
- [x] Wrong style
![image](https://github.com/Koniverse/web3-onboard/assets/11567273/31a6c13d-3af3-48b3-b49a-cf4aa3c4bb11)

**Comment by haiyenvu23** [comment]
Temporarily hiding this section
